### PR TITLE
electron wrapper

### PR DESCRIPTION
**Pull request by michalCapo**

### CODE REVIEW

**Comment by petersirka** [comment]
I think that better will be to create a new repository for example `nosqlviewerelectron`.... I'll create it.

**Comment by petersirka** [comment]
Don't close this.

**Comment by michalCapo** [comment]
I would like to ask about state on this.

**Comment by michalCapo** [comment]
Created https://github.com/michalCapo/nosqlviewerapp for this purpose (not included here)

**Pull request closed without merging**
